---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
_2fa\Extensions\Member:
  validated_activation_mode: true
HtmlEditorField:
  use_gzip: false
SSViewer:
  theme: 'simple'
Blog:
  extensions:
    - WidgetPageExtension
BlogPost:
  extensions:
    - WidgetPageExtension
Brand:
  extensions:
    - SubsiteModelExtension
BrandAdmin:
  extensions:
    - SubsiteMenuExtension
